##### Joystick
path/joystick:       "/dev/input/js0"
#devices/mti:            "/dev/ttyS4"   # P1 on adapter
#devices/mti:            "/dev/ttyUSB1" 
#devices/mti:            "/dev/xsens" 

control/joystick/logitechf710: 1
control/joystick/ducttape: 0
control/joystick/predator: 0
control/joystick/firejet:  0

##### Logging
log/interval:           0.01
log/timestamp:          "timestamps.txt"
log/bagfile:            "log.bag"
log/rxpfile:            "raw.rxp"
log/basedir:            "/tmp/"
