# VMC Controller (Irma, Lars)
devices/controller:     "VMC"
devices/volksbot:       "/dev/volksbot"
odometry/wheel_base:    44.4
odometry/ticks_per_cm:  -461.817

# Laser-Scanner (Sick)
sick/ip:                "192.168.0.9"
