# Simulator Controller
devices/controller:      "SIM"
odometry/wheel_base:     44.4 # CHANGE THIS TO MATCH SIM CONTROLLER
odometry/ticks_per_cm:   -1811.9178 # CHANGE THIS TO MATCH SIM CONTROLLER

# Laser-Scanner (Sick)
sick/ip:                 "0.0.0.0" # like "do not use"
